name: Ruff lint and format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Ruff settings are stored in pyproject.toml
  ruff:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Format code with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: format .

      - name: Lint code with Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check --fix --exit-zero .  # --exit-zero to ignore unsave fixes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Ruff: auto-format and auto-lint"
          commit_options: '--no-verify'
